project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: false
  apaquarto-docx: default
  apaquarto-pdf:
   documentmode: jou
   keep-tex: true
    

execute:
  freeze: auto


