project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: false
    toc-depth: 3
  apaquarto-docx: default
  apaquarto-pdf: default

execute:
  freeze: auto


